#Stie Wide configuration

theme: jekyll-theme-architect
title: Website of Samantha Sword-Fehlberg
description: Ph.D. Researcher 
locale: en_US

#Some Specifiers
owner:
  name: Samantha Sword-Fehlberg
  avatar: bio-photo.jpg
  email: ssfehlberg@gmail.com
  linkedin: Samantha Sword-Fehlberg
  github: ssfehlberg
  orcid: 0000-0001-8557-8132
  researchgate: Samantha Sword-Fehlberg
  
